---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cacheruntimeclasses.data.fluid.io
spec:
  group: data.fluid.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              fileSystemType:
                type: string
              topology:
                type: object
                properties:
                  master:
                    type: object
                    properties:
                      workloadType:
                        type: object
                        properties:
                          apiVersion:
                            type: string
                          kind:
                            type: string
                      service:
                        type: object
                        properties:
                          headless:
                            type: object
                      dependencies:
                        type: object
                        properties:
                          encryptOption:
                            type: object
                      podTemplateSpec:
                        type: object
                        properties:
                          spec:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                      volumeClaimTemplates:
                        type: array
                        items:
                          type: object
                          properties:
                            metadata:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                            spec:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                  worker:
                    type: object
                    properties:
                      workloadType:
                        type: object
                        properties:
                          apiVersion:
                            type: string
                          kind:
                            type: string
                      service:
                        type: object
                        properties:
                          headless:
                            type: object
                      dependencies:
                        type: object
                      podTemplateSpec:
                        type: object
                        properties:
                          spec:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                      volumeClaimTemplates:
                        type: array
                        items:
                          type: object
                          properties:
                            metadata:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                            spec:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                  client:
                    type: object
                    properties:
                      workloadType:
                        type: object
                        properties:
                          apiVersion:
                            type: string
                          kind:
                            type: string
                      dependencies:
                        type: object
                        properties:
                          encryptOption:
                            type: object
                      podTemplateSpec:
                        type: object
                        properties:
                          spec:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
  scope: Cluster
  names:
    plural: cacheruntimeclasses
    singular: cacheruntimeclass
    kind: CacheRuntimeClass

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cacheruntimes.data.fluid.io
spec:
  group: data.fluid.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              runtimeClassName:
                type: string
              master:
                type: object
                properties:
                  options:
                    type: object
                    additionalProperties:
                      type: string
                  replicas:
                    type: integer
              worker:
                type: object
                properties:
                  options:
                    type: object
                    additionalProperties:
                      type: string
                  replicas:
                    type: integer
                  tieredStore:
                    type: object
                    properties:
                      levels:
                        type: array
                        items:
                          type: object
                          properties:
                            quota:
                              type: string
                            low:
                              type: string
                            high:
                              type: string
                            path:
                              type: string
                            medium:
                              type: object
                              properties:
                                emptyDir:
                                  type: object
                                  properties:
                                    medium:
                                      type: string
                                    sizeLimit:
                                      type: string
              client:
                type: object
                properties:
                  options:
                    type: object
                    additionalProperties:
                      type: string
                  volumeMounts:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        mountPath:
                          type: string
              volumes:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    emptyDir:
                      type: object
                      properties:
                        sizeLimit:
                          type: string
          status:
            type: object
            properties:
              phase:
                type: string
              conditions:
                type: array
                items:
                  type: object
  scope: Namespaced
  names:
    plural: cacheruntimes
    singular: cacheruntime
    kind: CacheRuntime
