[package]
name = "orpc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "High-performance network communication framework."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
orpc-rpc = { workspace = true }
