[package]
name = "curvine-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
curvine-common-core = { workspace = true }

[features]
jemalloc = ["curvine-common-core/jemalloc"]
mimalloc = ["curvine-common-core/mimalloc"]
system = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }
