apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: curvine-csi-node-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: curvine-csi-node-role
subjects:
  - kind: ServiceAccount
    name: curvine-csi-node-sa
    namespace: curvine-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: curvine-csi-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: curvine-csi-controller-role
subjects:
  - kind: ServiceAccount
    name: curvine-csi-controller-sa
    namespace: curvine-system
