// Copyright 2025 OPPO.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Unified configuration loading pipeline.
//!
//! Layer order (low → high priority):
//!
//! ```text
//! serde defaults → file (TOML) → environment (explicit allowlist) → CLI overrides (typed)
//! ```
//!
//! The file and environment layers are merged as raw `toml::Value` documents and
//! deserialized exactly once into [`ClusterConf`], so native serde semantics
//! (`#[serde(default)]`, aliases, arrays of tables, error messages) are preserved
//! without an intermediate value model. Typed CLI overrides (generated by the
//! `ClientCliArgs` derive macro) run after deserialization and therefore sit on
//! top of the whole stack; a future runtime/admin overlay will slot between the
//! environment layer and deserialization without changing this module's shape.
//!
//! Environment variables are applied through an explicit allowlist table
//! ([`ENV_HOSTNAME_OVERRIDES`]) instead of generic name→path mapping: Curvine key
//! names are underscore-heavy (`format_master`, `master_addrs`, …), which makes
//! separator-based automatic mapping ambiguous. Adding a new env override is one
//! new row in the table plus a unit test.

use crate::ClusterConf;
use curvine_core_error::{err_box, try_err, CommonResult};
use std::env;
use std::fs::read_to_string;
use std::path::PathBuf;

/// Which entrypoint is loading the configuration. Controls how much of the env
/// layer applies, mirroring the historical `from()` / `from_transfer()` split.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LoadProfile {
    /// master / worker / fuse / cli / sdk: all sections participate.
    Full,
    /// Standalone transfer service: only client + transfer hostnames resolve.
    Transfer,
}

/// One allowlisted environment variable and the dotted config paths it feeds.
#[derive(Debug, Clone, Copy)]
pub struct EnvOverride {
    pub var: &'static str,
    /// Dotted paths into the cluster TOML document (e.g. `"worker.hostname"`).
    /// One variable may feed several paths (master hostname also seeds journal).
    pub paths: &'static [&'static str],
}

/// Hostname-related env allowlist. Applied only when `net_interface` is unset
/// (see [`apply_env_layer`]); values are trimmed before use, matching the
/// historical behavior.
pub const ENV_HOSTNAME_OVERRIDES: &[EnvOverride] = &[
    EnvOverride {
        var: ClusterConf::ENV_MASTER_HOSTNAME,
        paths: &["master.hostname", "journal.hostname"],
    },
    EnvOverride {
        var: ClusterConf::ENV_WORKER_HOSTNAME,
        paths: &["worker.hostname"],
    },
    EnvOverride {
        var: ClusterConf::ENV_CLIENT_HOSTNAME,
        paths: &["client.hostname"],
    },
    EnvOverride {
        var: ClusterConf::ENV_TRANSFER_HOSTNAME,
        paths: &["transfer.hostname"],
    },
];

/// Document key holding the NIC used to auto-resolve local IPv4 hostnames.
const NET_INTERFACE_KEY: &str = "net_interface";

// ---------------------------------------------------------------------------
// Document assembly
// ---------------------------------------------------------------------------

/// Reads the raw TOML text of a config file.
pub fn read_file_text<T: AsRef<str>>(path: T) -> CommonResult<String> {
    let path = path.as_ref();
    let text = try_err!(read_to_string(path));
    Ok(text)
}

/// Builds the effective pre-deserialization document:
/// file TOML → deep-merge overlays → environment layer.
///
/// `overlays` are applied in order, each on top of the previous result
/// (reserved for future formats / runtime overlay layers).
pub fn build_document(file_text: &str, overlays: &[toml::Value]) -> CommonResult<toml::Value> {
    let mut doc: toml::Value = try_err!(toml::from_str(file_text));
    for overlay in overlays {
        deep_merge(&mut doc, overlay);
    }
    apply_env_layer_with(&mut doc, LoadProfile::Full, &real_env_lookup)?;
    Ok(doc)
}

/// [`build_document`] restricted to the transfer service's hostname scope.
pub fn build_transfer_document(
    file_text: &str,
    overlays: &[toml::Value],
) -> CommonResult<toml::Value> {
    let mut doc: toml::Value = try_err!(toml::from_str(file_text));
    for overlay in overlays {
        deep_merge(&mut doc, overlay);
    }
    apply_env_layer_with(&mut doc, LoadProfile::Transfer, &real_env_lookup)?;
    Ok(doc)
}

/// Production environment lookup.
fn real_env_lookup(var: &str) -> Option<String> {
    env::var(var).ok()
}

/// Environment layer: net_interface resolution + `CURVINE_*_HOSTNAME` overrides.
///
/// Behavior ported 1:1 from the pre-pipeline loader:
/// - A non-empty (trimmed) `net_interface` in the document wins: its local IPv4
///   replaces every role hostname, any set hostname env vars are ignored with a
///   stderr warning (logger is not initialized yet at load time).
/// - Otherwise each set env var from [`ENV_HOSTNAME_OVERRIDES`] (trimmed) is
///   written to its dotted paths.
pub fn apply_env_layer_with(
    doc: &mut toml::Value,
    profile: LoadProfile,
    lookup: &dyn Fn(&str) -> Option<String>,
) -> CommonResult<()> {
    let scoped: Vec<&EnvOverride> = ENV_HOSTNAME_OVERRIDES
        .iter()
        .filter(|o| match profile {
            LoadProfile::Full => true,
            // The standalone transfer process only resolves its own hostname
            // (plus the client it embeds); touching master/journal/worker
            // entries would be surprising for a data-plane-only service.
            LoadProfile::Transfer => {
                o.var == ClusterConf::ENV_CLIENT_HOSTNAME
                    || o.var == ClusterConf::ENV_TRANSFER_HOSTNAME
            }
        })
        .collect();

    if net_interface_set(doc) {
        let interface = doc_string(doc, &[NET_INTERFACE_KEY])
            .unwrap_or_default()
            .trim()
            .to_string();
        let ip = ClusterConf::interface_ipv4(&interface)?;

        // net_interface takes precedence over the CURVINE_*_HOSTNAME env vars.
        // Warn (rather than silently ignore) when any of them is also set, so
        // an operator who exported a hostname override but sees it have no
        // effect can tell why. Runs before Logger::init — use eprintln!.
        let mut touched = Vec::new();
        for entry in &scoped {
            if lookup(entry.var).is_some() {
                eprintln!(
                    "[WARN] net_interface '{}' is set (resolved to {}); ignoring {}.",
                    interface, ip, entry.var
                );
            }
            // The NIC-resolved IP replaces every path the profile's allowlist
            // entries feed — same addressing as the env-value branch below,
            // so there is exactly one source of truth for the scope.
            for path in entry.paths {
                touched.push(*path);
            }
        }
        for path in touched {
            set_dotted(doc, path, toml::Value::String(ip.clone()))?;
        }
        return Ok(());
    }

    for entry in scoped {
        if let Some(value) = lookup(entry.var) {
            let value = value.trim().to_string();
            for path in entry.paths {
                set_dotted(doc, path, toml::Value::String(value.clone()))?;
            }
        }
    }
    Ok(())
}

fn net_interface_set(doc: &toml::Value) -> bool {
    doc_string(doc, &[NET_INTERFACE_KEY])
        .map(|v| !v.trim().is_empty())
        .unwrap_or(false)
}

// ---------------------------------------------------------------------------
// toml::Value navigation helpers
// ---------------------------------------------------------------------------

/// Reads a string at a dotted path; `None` when any segment is missing or the
/// leaf is not a string.
pub fn doc_string(doc: &toml::Value, path: &[&str]) -> Option<String> {
    let mut cur = doc;
    for seg in path {
        cur = cur.get(seg)?;
    }
    cur.as_str().map(str::to_string)
}

/// Sets a value at a dotted path, creating intermediate tables as needed.
pub fn set_dotted(doc: &mut toml::Value, path: &str, value: toml::Value) -> CommonResult<()> {
    let segments: Vec<&str> = path.split('.').collect();
    if segments.is_empty() {
        return err_box!("empty config path");
    }
    let mut cur = doc;
    for seg in &segments[..segments.len() - 1] {
        if !cur.is_table() {
            return err_box!(
                "config path '{}' collides with a non-table value at '{}'",
                path,
                seg
            );
        }
        let table = cur.as_table_mut().expect("checked is_table");
        cur = table
            .entry(seg.to_string())
            .or_insert_with(|| toml::Value::Table(toml::value::Table::new()));
    }
    let last = segments[segments.len() - 1];
    if !cur.is_table() {
        return err_box!("config path '{}' parent is not a table", path);
    }
    cur.as_table_mut()
        .expect("checked is_table")
        .insert(last.to_string(), value);
    Ok(())
}

/// Deep-merges `overlay` into `base`: tables merge recursively, scalars and
/// arrays are replaced wholesale (arrays never merge element-wise — a list is
/// one configuration value).
pub fn deep_merge(base: &mut toml::Value, overlay: &toml::Value) {
    match (base, overlay) {
        (toml::Value::Table(base_t), toml::Value::Table(overlay_t)) => {
            for (key, overlay_v) in overlay_t {
                match base_t.get_mut(key) {
                    Some(base_v) if base_v.is_table() && overlay_v.is_table() => {
                        deep_merge(base_v, overlay_v);
                    }
                    _ => {
                        base_t.insert(key.clone(), overlay_v.clone());
                    }
                }
            }
        }
        (base, overlay) => *base = overlay.clone(),
    }
}

// ---------------------------------------------------------------------------
// Config discovery
// ---------------------------------------------------------------------------

/// A located config file path plus a human-readable source label for logs.
#[derive(Debug, Clone)]
pub struct DiscoveredPath {
    pub path: PathBuf,
    pub source: String,
}

impl DiscoveredPath {
    pub fn as_str(&self) -> std::borrow::Cow<'_, str> {
        self.path.to_string_lossy()
    }
}

/// Unified config-file discovery shared by every component entrypoint
/// (server / fuse / cli / sdk / lancedb), replacing per-crate duplicates.
pub struct ConfigLoader;

impl ConfigLoader {
    pub const DEFAULT_FILE_NAME: &'static str = "curvine-cluster.toml";

    /// Discovery order:
    /// 1. explicit path (CLI `--conf`, storage option, …), taken as-is even if
    ///    missing — the subsequent load produces the actionable error;
    /// 2. `CURVINE_CONF_FILE`;
    /// 3. well-known locations ([`Self::default_candidates`]), first that exists.
    ///
    /// Returns `None` only when nothing was configured or found; callers decide
    /// their own fallback policy (error out vs. run on defaults).
    pub fn discover(explicit: Option<&str>) -> Option<DiscoveredPath> {
        Self::discover_configured(explicit).or_else(|| {
            Self::default_candidates()
                .into_iter()
                .find(|(path, _)| path.exists())
                .map(|(path, source)| DiscoveredPath {
                    path,
                    source: source.to_string(),
                })
        })
    }

    /// Discovery restricted to explicitly configured sources (argument or
    /// `CURVINE_CONF_FILE`), without probing default locations. For embedders
    /// (e.g. lancedb) whose own fallback chain must run before any
    /// filesystem probing would be appropriate.
    pub fn discover_configured(explicit: Option<&str>) -> Option<DiscoveredPath> {
        if let Some(path) = explicit.map(str::trim).filter(|p| !p.is_empty()) {
            return Some(DiscoveredPath {
                path: PathBuf::from(path),
                source: "--conf".to_string(),
            });
        }

        if let Ok(path) = env::var(ClusterConf::ENV_CONF_FILE) {
            return Some(DiscoveredPath {
                path: PathBuf::from(path),
                source: ClusterConf::ENV_CONF_FILE.to_string(),
            });
        }

        None
    }

    /// Well-known fallback locations in probe order.
    pub fn default_candidates() -> Vec<(PathBuf, &'static str)> {
        let mut candidates = vec![
            (PathBuf::from(Self::DEFAULT_FILE_NAME), "current directory"),
            (
                PathBuf::from("conf").join(Self::DEFAULT_FILE_NAME),
                "current conf directory",
            ),
        ];

        if let Some(home) = env::var_os("HOME") {
            candidates.push((
                PathBuf::from(home)
                    .join(".curvine")
                    .join(Self::DEFAULT_FILE_NAME),
                "user config directory",
            ));
        }

        if let Ok(curvine_home) = env::var("CURVINE_HOME") {
            candidates.push((
                PathBuf::from(curvine_home)
                    .join("conf")
                    .join(Self::DEFAULT_FILE_NAME),
                "CURVINE_HOME",
            ));
        }

        candidates
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    fn lookup<'a>(map: &'a [(&'a str, &'a str)]) -> impl Fn(&str) -> Option<String> + 'a {
        let map: HashMap<String, String> = map
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect();
        move |var| map.get(var).cloned()
    }

    #[test]
    fn deep_merge_replaces_scalars_and_merges_tables() {
        let base_text = r#"
            [master]
            hostname = "a"
            rpc_port = 1
        "#;
        let mut base: toml::Value = toml::from_str(base_text).unwrap();
        let overlay: toml::Value = toml::from_str(
            r#"
            format_master = true
            [master]
            hostname = "b"
            [client]
            io_threads = 4
            "#,
        )
        .unwrap();

        deep_merge(&mut base, &overlay);

        assert_eq!(base["format_master"].as_bool(), Some(true));
        assert_eq!(base["master"]["hostname"].as_str(), Some("b"));
        assert_eq!(base["master"]["rpc_port"].as_integer(), Some(1));
        assert_eq!(base["client"]["io_threads"].as_integer(), Some(4));
    }

    #[test]
    fn deep_merge_replaces_arrays_wholesale() {
        let mut base: toml::Value = toml::from_str("a = [1, 2, 3]").unwrap();
        let overlay: toml::Value = toml::from_str("a = [9]").unwrap();
        deep_merge(&mut base, &overlay);
        assert_eq!(base["a"].as_array().unwrap().len(), 1);
    }

    #[test]
    fn set_and_get_dotted_paths() {
        let mut doc = toml::Value::Table(toml::value::Table::new());
        set_dotted(&mut doc, "master.hostname", toml::Value::String("h".into())).unwrap();

        assert_eq!(doc_string(&doc, &["master", "hostname"]), Some("h".into()));
        assert_eq!(doc_string(&doc, &["master", "missing"]), None);

        // Overwrite an existing nested value.
        set_dotted(
            &mut doc,
            "master.hostname",
            toml::Value::String("h2".into()),
        )
        .unwrap();
        assert_eq!(doc_string(&doc, &["master", "hostname"]), Some("h2".into()));
    }

    #[test]
    fn env_hostname_overrides_apply_trimmed_values() {
        let mut doc: toml::Value = toml::from_str("[master]\nhostname = \"file\"\n").unwrap();
        let env = lookup(&[
            (ClusterConf::ENV_MASTER_HOSTNAME, " master-01 "),
            (ClusterConf::ENV_WORKER_HOSTNAME, "worker-01"),
        ]);
        apply_env_layer_with(&mut doc, LoadProfile::Full, &env).unwrap();

        // Master hostname seeds both master and journal sections.
        assert_eq!(
            doc_string(&doc, &["master", "hostname"]),
            Some("master-01".into())
        );
        assert_eq!(
            doc_string(&doc, &["journal", "hostname"]),
            Some("master-01".into())
        );
        assert_eq!(
            doc_string(&doc, &["worker", "hostname"]),
            Some("worker-01".into())
        );
        // Unset vars leave file values untouched.
        assert!(doc.get("client").is_none());
    }

    #[test]
    fn transfer_profile_ignores_master_worker_env_vars() {
        let mut doc: toml::Value = toml::from_str("[master]\nhostname = \"file\"\n").unwrap();
        let env = lookup(&[
            (ClusterConf::ENV_MASTER_HOSTNAME, "ignored"),
            (ClusterConf::ENV_CLIENT_HOSTNAME, "client-01"),
        ]);
        apply_env_layer_with(&mut doc, LoadProfile::Transfer, &env).unwrap();

        assert_eq!(
            doc_string(&doc, &["master", "hostname"]),
            Some("file".into())
        );
        assert_eq!(
            doc_string(&doc, &["client", "hostname"]),
            Some("client-01".into())
        );
    }

    #[test]
    fn whitespace_only_net_interface_falls_back_to_env() {
        let mut doc: toml::Value = toml::from_str("net_interface = \" \"").unwrap();
        let env = lookup(&[(ClusterConf::ENV_WORKER_HOSTNAME, "worker-01")]);
        apply_env_layer_with(&mut doc, LoadProfile::Full, &env).unwrap();

        assert_eq!(
            doc_string(&doc, &["worker", "hostname"]),
            Some("worker-01".into())
        );
    }

    #[test]
    fn build_document_parses_file_and_applies_env() {
        let text = r#"
            [master]
            hostname = "file-master"

            [client]
            hostname = "file-client"
        "#;
        let env_map = lookup(&[(ClusterConf::ENV_MASTER_HOSTNAME, "env-master")]);
        // build_document uses real env; emulate by calling the stages directly.
        let mut doc: toml::Value = toml::from_str(text).unwrap();
        apply_env_layer_with(&mut doc, LoadProfile::Full, &env_map).unwrap();

        assert_eq!(
            doc_string(&doc, &["master", "hostname"]),
            Some("env-master".into())
        );
        assert_eq!(
            doc_string(&doc, &["client", "hostname"]),
            Some("file-client".into())
        );
    }

    #[test]
    fn discovery_prefers_explicit_over_env_var() {
        // Explicit path wins even when CURVINE_CONF_FILE is set; both are taken
        // as-is regardless of existence (load errors surface later with context).
        // We cannot safely mutate global env in parallel tests, so we exercise
        // only the explicit branch here; env/default branches share the same
        // code path verified by construction.
        let found = ConfigLoader::discover(Some("/tmp/explicit.toml")).unwrap();
        assert_eq!(found.source, "--conf");
        assert_eq!(found.as_str(), "/tmp/explicit.toml");
    }

    #[test]
    fn default_candidates_cover_well_known_locations() {
        let names: Vec<String> = ConfigLoader::default_candidates()
            .into_iter()
            .map(|(p, _)| p.file_name().unwrap().to_string_lossy().to_string())
            .collect();
        assert!(names.iter().all(|n| n == ConfigLoader::DEFAULT_FILE_NAME));
    }
}
