---
apiVersion: v1
kind: ConfigMap
metadata:
  name: curvine-conf
  namespace: curvine
data:
  curvine-cluster.toml: |
    format_master = false
    format_worker = false
    cluster_id = "curvine"

    [master]
    rpc_port = 8995
    meta_dir = "./data/meta"
    audit_logging_enabled = true
    log = { level = "info", log_dir = "./logs", file_name = "master.log" }

    [journal]
    rpc_port = 8996
    journal_addrs = [
        # {id = 1, hostname = "cv-master-0.cv-master.curvine.svc.cluster.local", port = 8996},
        # {id = 1, hostname = "cv-master-0.svc.cluster.local", port = 8996},
        {id = 1, hostname = "localhost", port = 8996}
    ]
    journal_dir = "./data/journal"

    [worker]
    rpc_port = 8997
    web_port = 9000
    dir_reserved = "10GB"
    data_dir = [
        "[SSD]/data/data1",
    ]
    log = { level = "info", log_dir = "./logs", file_name = "worker.log" }


    [client]
    master_addrs = [
       {id = 1, hostname = "cv-master-svc", port = 8995}
    ]

    [fuse]
    debug = false


    [log]
    level = "info"
    log_dir = "./logs"
    file_name = "client.log"

---
apiVersion: v1
kind: Service
metadata:
  name: cv-master
  labels:
    role: cv-master-svc
  namespace: curvine
spec:
  ports:
    - name: rpc
      port: 8995
      targetPort: 8995
      protocol: TCP
    - name: journal
      port: 8996
      targetPort: 8996
      protocol: TCP
    - name: web
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: web1
      port: 9001
      targetPort: 9001
      protocol: TCP
    - name: worker
      port: 8997
      targetPort: 8997
      protocol: TCP
  clusterIP: None 
  selector:
    role: cv-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cv-master
  labels:
    role: cv-master
  namespace: curvine
spec:
  replicas: 1
  selector:
    matchLabels:
      role: cv-master
  serviceName: "cv-master"
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        role: cv-master
    spec:
      setHostnameAsFQDN: true
      containers:
        - name: cv-master
          image: curvine:latest
          imagePullPolicy: IfNotPresent
          args:
            - master
          volumeMounts:
          - name: curvine-conf
            mountPath: /opt/curvine/conf/curvine-cluster.toml
            subPath: curvine-cluster.toml
      volumes:
        - name: curvine-conf
          configMap:
            name: curvine-conf
            items:
            - key: curvine-cluster.toml
              path: curvine-cluster.toml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cv-worker
  labels:
    role: cv-worker
  namespace: curvine
spec:
  replicas: 1
  selector:
    matchLabels:
      role: cv-worker
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        role: cv-worker
    spec:
      containers:
        - name: cv-worker
          image: curvine:latest
          imagePullPolicy: IfNotPresent
          args:
            - worker
          volumeMounts:
          - name: curvine-conf
            mountPath: /opt/curvine/conf/curvine-cluster.toml
            subPath: curvine-cluster.toml
      volumes:
        - name: curvine-conf
          configMap:
            name: curvine-conf
            items:
            - key: curvine-cluster.toml
              path: curvine-cluster.toml