name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Whether to push image to GitHub Container Registry'
        required: false
        default: false
        type: boolean
      use_cache:
        description: 'Whether to build image with dependency cache'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        if: inputs.push_image == true
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.PAT_GITHUB_TOKEN }}
      
      - name: Login to Docker Hub
        if: inputs.push_image == true
        uses: docker/login-action@v3
        with:
          username: curvine
          password: ${{ secrets.PAT_DOCKERIO_TOKEN }}
      
      - name: Build and push Docker image (standard)
        if: inputs.use_cache == false
        uses: docker/build-push-action@v5
        with:
          context: ./curvine-docker/compile
          file: ./curvine-docker/compile/Dockerfile_rocky9
          push: ${{ inputs.push_image }}
          tags: |
            ghcr.io/curvineio/curvine-compile:latest
            curvine/curvine-compile:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push Docker image (with cache)
        if: inputs.use_cache == true
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./curvine-docker/compile/Dockerfile_rocky9_cached
          push: ${{ inputs.push_image }}
          tags: |
            ghcr.io/curvineio/curvine-compile:build-cached
            curvine/curvine-compile:build-cached
          cache-from: type=gha
          cache-to: type=gha,mode=max